### ISSUE TITLE
Consumir feriados de una API, Eliminar hardcoded

### ISSUE THREAD

**Issue by poleselfg** [nixietab/Feriado#2]
Un buen avance sería consumir los feriados de una API, y eliminar los hardcoded. 

Por ejemplo : https://datos.gob.ar/apis

**Comment by zedeme** [comment]
Eso lo fixea #4

**Comment by zedeme** [comment]
Eso lo fixea #4

**Comment by zedeme** [comment]
Eso lo fixea #4

**Comment by zedeme** [comment]
Eso lo fixea #4

**Comment by zedeme** [comment]
Eso lo fixea #4

**Comment by zedeme** [comment]
Eso lo fixea #4

**Comment by zedeme** [comment]
Eso lo fixea #4
