### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by Anerak** [nixietab/Feriado#3]
El body tiene un overflow, asumo que por el `height: 100vh`.
Agregando `overflow: hidden` al CSS hace que desaparezcan la barra de scroll (que no tiene propósito actualmente)

![image](https://github.com/nixietab/Feriado/assets/11636440/30a95837-b83c-4b82-a12f-ad425dc2fabf)

**Comment by nixietab** [comment]
Arreglado en la próxima versión
